name: Init Labels

on:
  workflow_dispatch:

jobs:
  update-labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const core = require('@actions/core');
            const { owner, repo } = context.repo;
            const labelsPath = path.join(process.env.GITHUB_WORKSPACE, '.github', 'labels.json');
            const labels = JSON.parse(fs.readFileSync(labelsPath, 'utf8'));

            for (const l of labels) {
              try {
                await github.rest.issues.createLabel({ owner, repo, name: l.name, color: l.color, description: l.description || '' });
                core.info(`Created label: ${l.name}`);
              } catch (e) {
                if (e.status === 422) {
                  // Already exists – update it
                  await github.rest.issues.updateLabel({ owner, repo, name: l.name, color: l.color, description: l.description || '' });
                  core.info(`Updated label: ${l.name}`);
                } else {
                  core.warning(`Failed for ${l.name}: ${e.message}`);
                }
              }
            }
