name: Init Milestones

on:
  workflow_dispatch:

jobs:
  update-milestones:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const core = require('@actions/core');
            const { owner, repo } = context.repo;
            const msPath = path.join(process.env.GITHUB_WORKSPACE, '.github', 'milestones.json');
            const milestones = JSON.parse(fs.readFileSync(msPath, 'utf8'));

            // Fetch existing milestones
            const existing = await github.paginate(github.rest.issues.listMilestones, { owner, repo, state: 'all' });
            const map = new Map(existing.map(m => [m.title, m]));

            for (const m of milestones) {
              if (map.has(m.title)) {
                const cur = map.get(m.title);
                await github.rest.issues.updateMilestone({ owner, repo, milestone_number: cur.number, state: m.state || 'open', title: m.title, description: m.description || '' });
                core.info(`Updated milestone: ${m.title}`);
              } else {
                await github.rest.issues.createMilestone({ owner, repo, title: m.title, state: m.state || 'open', description: m.description || '' });
                core.info(`Created milestone: ${m.title}`);
              }
            }
